variable "vm_name" {}
variable "azurerm_resource_group" {}
variable "subnet_name" {}
variable "subnet_virtual_network_name" {}
variable "network_azurerm_resource_group" {}
variable "vm_size" {}
variable "additional_tags" {}
variable "managed_disk_id" {}
variable "managed_disk_type" {}